# Numpy Exercise

1) Create a 1D array of the even numbers from 2 to 40 inclusive using two different methods.

In [2]:
import numpy as np

In [3]:
# Method 1: Using arange()
even_numbers_1 = np.arange(2, 41, 2)

# Method 2: Using range() and converting to NumPy array
even_numbers_2 = np.array(range(2, 41, 2))

print(even_numbers_1)
print(even_numbers_2)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


2) Create a 3x3 identity-like array but with 5s on the diagonal.

In [4]:
array = np.eye(3) * 5

print(array)

[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]


3) Generate a 5x4 matrix of random integers from 10 to 99, then compute column-wise max and the index of the min in each row.

In [5]:
# Random integers from 10 to 99
matrix = np.random.randint(10, 100, size=(5, 4))

print("Matrix:")
print(matrix)

# Maximum value of each column
column_max = matrix.max(axis=0)

# Index of the minimum value in each row
row_min_index = matrix.argmin(axis=1)

print("\nColumn-wise maximum:")
print(column_max)

print("\nIndex of minimum in each row:")
print(row_min_index)

Matrix:
[[25 35 23 33]
 [61 33 84 64]
 [59 53 82 21]
 [84 83 88 97]
 [52 31 84 68]]

Column-wise maximum:
[84 83 88 97]

Index of minimum in each row:
[2 1 3 1 1]


4) Given `a = np.arange(24)`, reshape it to shape `(4, 3, 2)`, then compute the sum along axis 2.

In [6]:
a = np.arange(24)

# Reshape into (4, 3, 2)
a_reshaped = a.reshape(4, 3, 2)

# Sum along axis 2
result = a_reshaped.sum(axis=2)

print(a_reshaped)
print("\nSum along axis 2:")
print(result)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

Sum along axis 2:
[[ 1  5  9]
 [13 17 21]
 [25 29 33]
 [37 41 45]]


5) Concatenate two arrays `p = [1,2,3]` and `q = [4,5,6]` as:
   - a) a single 1D array
   - b) a 2x3 stacked array
   - c) a 3x2 stacked array

In [7]:
p = np.array([1, 2, 3])
q = np.array([4, 5, 6])

In [8]:
result_1d = np.concatenate((p, q))

print(result_1d)

[1 2 3 4 5 6]


In [9]:
result_2x3 = np.vstack((p, q))

print(result_2x3)

[[1 2 3]
 [4 5 6]]


In [10]:
result_3x2 = np.column_stack((p, q))

print(result_3x2)

[[1 4]
 [2 5]
 [3 6]]


6) Split `np.arange(20)` into 3 nearly equal parts and sort each part descending.

In [11]:
numbers = np.arange(20)

# Split into 3 nearly equal parts
parts = np.array_split(numbers, 3)

# Sort each part in descending order
for part in parts:
    part.sort()
    print(part[::-1])

[6 5 4 3 2 1 0]
[13 12 11 10  9  8  7]
[19 18 17 16 15 14]


7) Demonstrate view vs copy by slicing and modifying the original array vs a copy.

In [12]:
original = np.array([1, 2, 3, 4, 5])

# View: shares data with the original array
view = original[1:4]

# Modify the original array
original[2] = 99

print("Original:", original)
print("View:", view)

Original: [ 1  2 99  4  5]
View: [ 2 99  4]


In [13]:
#copy
original = np.array([1, 2, 3, 4, 5])

# Copy: independent data
copy_array = original[1:4].copy()

# Modify the original array
original[2] = 99

print("Original:", original)
print("Copy:", copy_array)

Original: [ 1  2 99  4  5]
Copy: [2 3 4]
