<a id='1'></a>
## 1. 🌟 What is NumPy?

**NumPy** stands for **Numerical Python**. It is the **core library** for numerical and scientific computing in Python.

| Feature | Python List | NumPy Array |
|--------|-------------|-------------|
| Data Type | Mixed | Homogeneous (same type) |
| Memory | Stores pointers | Contiguous raw values |
| Speed | Slow | Up to 50x faster |
| Math Ops | Manual loops | Vectorized (no loops) |
| ND Support | Nested lists (messy) | Native N-dimensional |

> 💡 **Why does ML/DL need NumPy?**  
> Every dataset, every weight matrix in a neural network, every image — is a NumPy array (or a tensor built on top of it).

<a id='2'></a>
## 2. 📦 Installing & Importing NumPy

In [ ]:
# Install NumPy (run once if not installed)
# !pip install numpy

In [1]:
# Standard import convention — always use 'np' alias
import numpy as np

# Check version
print("NumPy version:", np.__version__)

NumPy version: 2.2.6


<a id='3'></a>
## 3. 🏗️ Creating NumPy Arrays

The core object in NumPy is the **ndarray** (N-dimensional array).

### 3.1 From Python Lists

In [2]:
# ── 1D Array (Vector) ──
arr_1d = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr_1d)
print("Type:", type(arr_1d))

1D Array: [10 20 30 40 50]
Type: <class 'numpy.ndarray'>


In [3]:
# ── 2D Array (Matrix) ──
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("2D Array (Matrix):")
print(arr_2d)

2D Array (Matrix):
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# ── 3D Array (Tensor) ──
# Think of this as 2 'layers', each with 3 rows and 4 columns
# In Deep Learning: (batch_size, height, width) for grayscale images
arr_3d = np.array([[[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]],
                   [[13, 14, 15, 16],
                    [17, 18, 19, 20],
                    [21, 22, 23, 24]]])
print("3D Array (Tensor):")
print(arr_3d)
print("Shape:", arr_3d.shape)  # (2, 3, 4)

3D Array (Tensor):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


In [5]:
# ── From a Python List variable ──
python_list = [5, 10, 15, 20]
numpy_array = np.array(python_list)
print("From list:", numpy_array)

From list: [ 5 10 15 20]


### 3.2 Speed Comparison: List vs NumPy

In [15]:
import time

size = 1_000_000

# Python List
py_list = list(range(size))
start = time.time()
result_list = [x * 2 for x in py_list]
list_time = time.time() - start

# NumPy Array
np_arr = np.arange(size)
start = time.time()
result_np = np_arr * 2
np_time = time.time() - start

print(f"Python List time : {list_time:.4f} seconds")
print(f"NumPy Array time : {np_time:.4f} seconds")
print(f"NumPy is {list_time / np_time:.1f}x faster!")

Python List time : 0.0698 seconds
NumPy Array time : 0.0030 seconds
NumPy is 23.2x faster!


<a id='4'></a>
## 4. 📊 Array Attributes: 
Array attributes are properties that provide information about a NumPy array, such as its size, dimensions, shape, and data type.

Every NumPy array has **built-in attributes** that describe it.

In [16]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Array:")
print(arr)
print()
print("── Attributes ──")
print(f"ndim   (dimensions)  : {arr.ndim}")       # number of axes
print(f"shape  (rows, cols)  : {arr.shape}")      # tuple of sizes
print(f"size   (total items) : {arr.size}")       # total number of elements
print(f"dtype  (data type)   : {arr.dtype}")      # type of elements
print(f"itemsize (bytes/elem): {arr.itemsize}")   # bytes per element
print(f"nbytes (total bytes) : {arr.nbytes}")     # total memory used
print(f"strides              : {arr.strides}")    # bytes to step in each dimension

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

── Attributes ──
ndim   (dimensions)  : 2
shape  (rows, cols)  : (3, 4)
size   (total items) : 12
dtype  (data type)   : int64
itemsize (bytes/elem): 8
nbytes (total bytes) : 96
strides              : (32, 8)


In [17]:
# ── ML Context: Image Shape ──
# A color image in ML is typically shaped as:
# (height, width, channels)  — e.g., (224, 224, 3) for RGB
# A batch of images: (batch_size, height, width, channels)

fake_image_batch = np.zeros((32, 224, 224, 3))  # 32 RGB images of 224x224
print("Image batch shape:", fake_image_batch.shape)
print("Total pixels per image:", 224 * 224 * 3)

Image batch shape: (32, 224, 224, 3)
Total pixels per image: 150528


<a id='5'></a>
## 5. 🔠 Array Data Types (dtype):
Array data types define the type of values stored inside a NumPy array.

NumPy supports many data types. Choosing the right one affects **memory** and **precision**.

In [18]:
# ── Common dtypes ──
print("Integer types:")
print("  int8  :", np.array([1], dtype=np.int8).dtype,   "| range: -128 to 127")
print("  int16 :", np.array([1], dtype=np.int16).dtype,  "| range: -32768 to 32767")
print("  int32 :", np.array([1], dtype=np.int32).dtype,  "| range: ~-2B to 2B")
print("  int64 :", np.array([1], dtype=np.int64).dtype,  "| range: very large")

print("\nFloat types:")
print("  float16:", np.array([1.0], dtype=np.float16).dtype, "| half precision")
print("  float32:", np.array([1.0], dtype=np.float32).dtype, "| single precision (ML default)")
print("  float64:", np.array([1.0], dtype=np.float64).dtype, "| double precision")

print("\nOther types:")
print("  bool   :", np.array([True], dtype=np.bool_).dtype)
print("  complex:", np.array([1+2j], dtype=np.complex64).dtype)

Integer types:
  int8  : int8 | range: -128 to 127
  int16 : int16 | range: -32768 to 32767
  int32 : int32 | range: ~-2B to 2B
  int64 : int64 | range: very large

Float types:
  float16: float16 | half precision
  float32: float32 | single precision (ML default)
  float64: float64 | double precision

Other types:
  bool   : bool
  complex: complex64


In [19]:
# ── Specifying dtype on creation ──
int_arr   = np.array([1, 2, 3], dtype=np.int32)
float_arr = np.array([1, 2, 3], dtype=np.float64)
bool_arr  = np.array([1, 0, 1, 0], dtype=np.bool_)

print("int32 array  :", int_arr,   "| dtype:", int_arr.dtype)
print("float64 array:", float_arr, "| dtype:", float_arr.dtype)
print("bool array   :", bool_arr,  "| dtype:", bool_arr.dtype)

int32 array  : [1 2 3] | dtype: int32
float64 array: [1. 2. 3.] | dtype: float64
bool array   : [ True False  True False] | dtype: bool


In [20]:
# ── Type Casting (astype) ──
arr = np.array([1.7, 2.9, 3.1, 4.8])
print("Original (float64):", arr)

arr_int = arr.astype(np.int32)     # truncates decimal part
print("Cast to int32     :", arr_int)

arr_bool = arr.astype(np.bool_)    # 0 → False, anything else → True
print("Cast to bool      :", arr_bool)

Original (float64): [1.7 2.9 3.1 4.8]
Cast to int32     : [1 2 3 4]
Cast to bool      : [ True  True  True  True]


In [21]:
# ── ML Note: Memory Impact of dtype ──
arr_f64 = np.ones((1000, 1000), dtype=np.float64)
arr_f32 = np.ones((1000, 1000), dtype=np.float32)

print(f"float64 array memory: {arr_f64.nbytes / 1e6:.1f} MB")
print(f"float32 array memory: {arr_f32.nbytes / 1e6:.1f} MB")
print("Using float32 cuts memory in HALF — crucial in deep learning!")

float64 array memory: 8.0 MB
float32 array memory: 4.0 MB
Using float32 cuts memory in HALF — crucial in deep learning!


<a id='6'></a>
## 6. 🏭 Array Initialization Functions:
Array initialization functions are NumPy functions used to create arrays with predefined values.

NumPy provides many convenient functions to **create arrays** without manually typing values.

### 6.1 Zeros, Ones, Full, Empty

In [22]:
# np.zeros — all elements = 0
z = np.zeros((3, 4))
print("zeros (3x4):")
print(z)

zeros (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
# np.ones — all elements = 1
o = np.ones((2, 5))
print("ones (2x5):")
print(o)

ones (2x5):
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
# np.full — all elements = specified value
f = np.full((3, 3), fill_value=7)
print("full (3x3) with 7:")
print(f)

full (3x3) with 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [29]:
# np.empty — uninitialized (random garbage values, very fast)
# USE ONLY when you plan to fill every element yourself
e = np.empty((2, 3))
print("empty (2x3) — contains garbage values:")
print(e)

empty (2x3) — contains garbage values:
[[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
# zeros_like, ones_like, full_like — same shape as existing array
original = np.array([[1, 2, 3], [4, 5, 6]])

print("zeros_like:")
print(np.zeros_like(original))

print("ones_like:")
print(np.ones_like(original))

print("full_like with 99:")
print(np.full_like(original, fill_value=99))

zeros_like:
[[0 0 0]
 [0 0 0]]
ones_like:
[[1 1 1]
 [1 1 1]]
full_like with 99:
[[99 99 99]
 [99 99 99]]


### 6.2 Identity & Eye

NumPy functions used to create special matrices:

np.identity(): Creates a square identity matrix with 1s on the main diagonal and 0s elsewhere.

np.eye(): Creates a 2D array with 1s on a specified diagonal and 0s elsewhere.

In [36]:
# np.eye — Identity matrix (diagonal = 1, rest = 0)
# Critical in linear algebra and ML weight initialization
eye = np.eye(4)  # 4x4 identity matrix
print("Identity matrix (4x4):")
print(eye)

Identity matrix (4x4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [37]:
# np.identity — same as eye for square matrices
identity = np.identity(3)
print("identity(3):")
print(identity)

identity(3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 6.3 Range-Based Arrays
Range-based arrays are NumPy arrays created from a sequence of numbers within a specified range using functions such as np.arange() and np.linspace().

In [38]:
# np.arange — like Python range() but returns array
# np.arange(start, stop, step)  — stop is EXCLUDED

print("arange(10)        :", np.arange(10))
print("arange(2, 10)     :", np.arange(2, 10))
print("arange(0, 1, 0.2) :", np.arange(0, 1, 0.2))   # float step
print("arange(10, 0, -2) :", np.arange(10, 0, -2))    # reverse

arange(10)        : [0 1 2 3 4 5 6 7 8 9]
arange(2, 10)     : [2 3 4 5 6 7 8 9]
arange(0, 1, 0.2) : [0.  0.2 0.4 0.6 0.8]
arange(10, 0, -2) : [10  8  6  4  2]


In [39]:
# np.linspace — evenly spaced values between start and stop
# np.linspace(start, stop, num)  — stop is INCLUDED
print("linspace(0, 1, 5)     :", np.linspace(0, 1, 5))
print("linspace(0, 10, 6)    :", np.linspace(0, 10, 6))
print("linspace(0, 1, 100)[:5]:", np.linspace(0, 1, 100)[:5], "...")

# ML use case: learning rate schedules, activation function plots
x = np.linspace(-5, 5, 1000)  # 1000 points for plotting sigmoid/relu

linspace(0, 1, 5)     : [0.   0.25 0.5  0.75 1.  ]
linspace(0, 10, 6)    : [ 0.  2.  4.  6.  8. 10.]
linspace(0, 1, 100)[:5]: [0.         0.01010101 0.02020202 0.03030303 0.04040404] ...


In [40]:
# np.logspace — logarithmically spaced values
# Values from 10^start to 10^stop
log = np.logspace(0, 3, 4)   # 10^0=1, 10^1=10, 10^2=100, 10^3=1000
print("logspace(0, 3, 4):", log)

# ML use case: trying learning rates [0.001, 0.01, 0.1, 1.0]
lr_search = np.logspace(-3, 0, 4)
print("Learning rate search:", lr_search)

logspace(0, 3, 4): [   1.   10.  100. 1000.]
Learning rate search: [0.001 0.01  0.1   1.   ]


<a id='7'></a>
## 7. 🔍 Basic Indexing & Slicing

<a id='7'></a>
## 7. 🔍 Basic Indexing & Slicing

Indexing: Accessing a specific element of an array using its position or index.

Slicing: Accessing a specific portion or range of elements from an array using a start, stop, and optional step.

### 7.1 1D Indexing :
1D indexing is accessing elements from a one-dimensional array using a single index.

In [41]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print("Array:", arr)

# Positive indexing (starts at 0)
print("arr[0]  =", arr[0])    # first element
print("arr[3]  =", arr[3])    # 4th element

# Negative indexing (starts from end)
print("arr[-1] =", arr[-1])   # last element
print("arr[-2] =", arr[-2])   # second to last

Array: [10 20 30 40 50 60 70 80]
arr[0]  = 10
arr[3]  = 40
arr[-1] = 80
arr[-2] = 70


In [42]:
# ── 1D Slicing: arr[start:stop:step] ──
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print("arr[2:5]   =", arr[2:5])     # index 2,3,4 (stop excluded)
print("arr[:4]    =", arr[:4])      # from start to index 3
print("arr[5:]    =", arr[5:])      # from index 5 to end
print("arr[::2]   =", arr[::2])     # every 2nd element
print("arr[::-1]  =", arr[::-1])    # reversed array
print("arr[1:7:2] =", arr[1:7:2])   # step of 2, from 1 to 6

arr[2:5]   = [30 40 50]
arr[:4]    = [10 20 30 40]
arr[5:]    = [60 70 80]
arr[::2]   = [10 30 50 70]
arr[::-1]  = [80 70 60 50 40 30 20 10]
arr[1:7:2] = [20 40 60]


### 7.2 2D Indexing:

2D indexing is accessing elements from a two-dimensional array using two indices: one for the row and one for the column.

In [43]:
matrix = np.array([[1,  2,  3,  4],
                   [5,  6,  7,  8],
                   [9,  10, 11, 12],
                   [13, 14, 15, 16]])
print("Matrix:")
print(matrix)
print()

# Single element: [row, col]
print("matrix[0, 0]  =", matrix[0, 0])   # top-left
print("matrix[1, 2]  =", matrix[1, 2])   # row 1, col 2
print("matrix[-1,-1] =", matrix[-1, -1]) # bottom-right

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

matrix[0, 0]  = 1
matrix[1, 2]  = 7
matrix[-1,-1] = 16


In [44]:
# ── 2D Slicing ──
print("Full row 1       :", matrix[1, :])        # entire row
print("Full col 2       :", matrix[:, 2])        # entire column
print("Rows 0-1, Cols 1-2:")
print(matrix[0:2, 1:3])                          # submatrix

print("\nTop-left 2x2 block:")
print(matrix[:2, :2])

print("\nBottom-right 2x2 block:")
print(matrix[2:, 2:])

Full row 1       : [5 6 7 8]
Full col 2       : [ 3  7 11 15]
Rows 0-1, Cols 1-2:
[[2 3]
 [6 7]]

Top-left 2x2 block:
[[1 2]
 [5 6]]

Bottom-right 2x2 block:
[[11 12]
 [15 16]]


### 7.3 Important: Views vs Copies

View: A new array that shares the same underlying data as the original array. Changes made to the view can affect the original array.

Copy: A completely independent duplicate of the original array. Changes made to the copy do not affect the original array.

In [45]:
# CRITICAL CONCEPT: Slicing returns a VIEW, not a copy!
original = np.array([1, 2, 3, 4, 5])
view     = original[1:4]          # this is a VIEW into original

print("Before modification:")
print("original:", original)
print("view    :", view)

view[0] = 999                     # modifying view affects original!

print("\nAfter modifying view[0] = 999:")
print("original:", original)      # original is changed too!
print("view    :", view)

Before modification:
original: [1 2 3 4 5]
view    : [2 3 4]

After modifying view[0] = 999:
original: [  1 999   3   4   5]
view    : [999   3   4]


In [46]:
# Use .copy() to get an independent copy
original = np.array([1, 2, 3, 4, 5])
copy     = original[1:4].copy()   # true independent copy

copy[0] = 999

print("After modifying copy[0] = 999:")
print("original:", original)      # original is NOT changed
print("copy    :", copy)

After modifying copy[0] = 999:
original: [1 2 3 4 5]
copy    : [999   3   4]


<a id='8'></a>
## 8. 🔄 Array Reshaping

Array reshaping is changing the dimensions or structure of an array without changing its elements.v

Reshaping is one of the **most used operations in ML/DL** — you constantly need to reshape data to fit model input requirements.

### 8.1 reshape()

In [47]:
arr = np.arange(1, 13)   # [1, 2, 3, ..., 12]
print("Original (1D, 12 elements):", arr)

# Reshape to 2D
reshaped_2d = arr.reshape(3, 4)   # 3 rows × 4 cols = 12 elements
print("\nReshaped to (3, 4):")
print(reshaped_2d)

# Reshape to 3D
reshaped_3d = arr.reshape(2, 2, 3)  # 2×2×3 = 12
print("\nReshaped to (2, 2, 3):")
print(reshaped_3d)

Original (1D, 12 elements): [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to (3, 4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped to (2, 2, 3):
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [48]:
# ── Using -1 to auto-calculate one dimension ──
arr = np.arange(24)

# Let NumPy figure out the number of columns
r1 = arr.reshape(4, -1)    # 4 rows, NumPy calculates cols = 24/4 = 6
r2 = arr.reshape(-1, 8)    # NumPy calculates rows = 24/8 = 3, 8 cols
r3 = arr.reshape(2, 3, -1) # 2×3 = 6, NumPy calculates last dim = 24/6 = 4

print("reshape(4, -1)  -> shape:", r1.shape)
print("reshape(-1, 8)  -> shape:", r2.shape)
print("reshape(2,3,-1) -> shape:", r3.shape)

reshape(4, -1)  -> shape: (4, 6)
reshape(-1, 8)  -> shape: (3, 8)
reshape(2,3,-1) -> shape: (2, 3, 4)


In [49]:
# ── ML Use Case: Flattening an image for a Dense layer ──
# A 28x28 grayscale image (like MNIST)
image = np.random.randint(0, 256, size=(28, 28))
print("Image shape:", image.shape)            # (28, 28)

# Flatten for a fully connected neural network input
flat = image.reshape(-1)       # or image.reshape(784)
print("Flattened shape:", flat.shape)         # (784,)

# Batch of images
batch = np.random.randint(0, 256, size=(64, 28, 28))  # 64 images
flat_batch = batch.reshape(64, -1)
print("Batch shape:", batch.shape)            # (64, 28, 28)
print("Flat batch shape:", flat_batch.shape)  # (64, 784)

Image shape: (28, 28)
Flattened shape: (784,)
Batch shape: (64, 28, 28)
Flat batch shape: (64, 784)


### 8.2 flatten() and ravel()

flatten(): Converts a multidimensional array into a one-dimensional array and returns a copy of the original data.

ravel(): Converts a multidimensional array into a one-dimensional array and usually returns a view of the original data when possible.

In [50]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# flatten() — returns a COPY (safe to modify)
flat = matrix.flatten()
print("flatten():", flat)

# ravel() — returns a VIEW (memory efficient, be careful)
raveled = matrix.ravel()
print("ravel()  :", raveled)

flatten(): [1 2 3 4 5 6]
ravel()  : [1 2 3 4 5 6]


### 8.3 Transpose

Transpose changes the rows of an array into columns and the columns into rows.

In [51]:
# Transpose flips rows and columns
A = np.array([[1, 2, 3],
              [4, 5, 6]])
print("A shape:", A.shape)          # (2, 3)
print("A:")
print(A)

print("\nA.T (transpose):")
print(A.T)                          # shape becomes (3, 2)
print("A.T shape:", A.T.shape)

# Alternative syntax
print("\nnp.transpose(A):")
print(np.transpose(A))

A shape: (2, 3)
A:
[[1 2 3]
 [4 5 6]]

A.T (transpose):
[[1 4]
 [2 5]
 [3 6]]
A.T shape: (3, 2)

np.transpose(A):
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# ── ML context: Transpose in matrix multiplication ──
# In neural networks: output = X @ W.T + b
# X shape: (batch_size, input_features)
# W shape: (output_features, input_features)
# W.T shape: (input_features, output_features)

X = np.random.randn(32, 784)   # batch of 32, each 784 features
W = np.random.randn(128, 784)  # weight matrix for 128 neurons

output = X @ W.T               # (32, 784) @ (784, 128) = (32, 128)
print("X shape     :", X.shape)
print("W shape     :", W.shape)
print("W.T shape   :", W.T.shape)
print("Output shape:", output.shape)  # (32, 128)

### 8.4 expand_dims and squeeze

expand_dims() adds a new dimension to an array at a specified axis.

squeeze() removes dimensions of size 1 from an array.

In [52]:
# expand_dims — add a new axis (very common in ML!)
arr = np.array([1, 2, 3, 4])     # shape (4,)
print("Original shape:", arr.shape)

# Add axis at position 0 → becomes a row vector
row = np.expand_dims(arr, axis=0)
print("expand_dims(axis=0):", row.shape)   # (1, 4)

# Add axis at position 1 → becomes a column vector
col = np.expand_dims(arr, axis=1)
print("expand_dims(axis=1):", col.shape)   # (4, 1)

# Alternative: using np.newaxis
row2 = arr[np.newaxis, :]    # same as expand_dims axis=0
col2 = arr[:, np.newaxis]    # same as expand_dims axis=1
print("arr[np.newaxis, :] shape:", row2.shape)
print("arr[:, np.newaxis] shape:", col2.shape)

Original shape: (4,)
expand_dims(axis=0): (1, 4)
expand_dims(axis=1): (4, 1)
arr[np.newaxis, :] shape: (1, 4)
arr[:, np.newaxis] shape: (4, 1)


In [53]:
# squeeze — remove dimensions of size 1
arr = np.array([[[1, 2, 3]]])   # shape (1, 1, 3)
print("Before squeeze:", arr.shape)

squeezed = np.squeeze(arr)
print("After squeeze :", squeezed.shape)    # (3,)

Before squeeze: (1, 1, 3)
After squeeze : (3,)


<a id='9'></a>
## 9. 🔧 Array Manipulation

Array manipulation refers to modifying the structure, shape, or arrangement of array elements using operations such as reshaping, transposing, splitting, joining, inserting, and deleting elements.

### 9.1 Concatenation

Concatenation is the process of joining two or more arrays together along a specified axis to create a single array.

In [54]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[7, 8, 9],
              [10, 11, 12]])

# Concatenate along axis=0 (stack vertically / add rows)
vertical = np.concatenate([a, b], axis=0)
print("concatenate axis=0 (vertical):")
print(vertical)
print("shape:", vertical.shape)   # (4, 3)

print()

# Concatenate along axis=1 (stack horizontally / add columns)
horizontal = np.concatenate([a, b], axis=1)
print("concatenate axis=1 (horizontal):")
print(horizontal)
print("shape:", horizontal.shape)  # (2, 6)

concatenate axis=0 (vertical):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
shape: (4, 3)

concatenate axis=1 (horizontal):
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
shape: (2, 6)


### 9.2 Stacking :

Stacking is the process of joining two or more arrays along a new axis to create a higher-dimensional array.

In [55]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# vstack — stack vertically (row-wise)
print("vstack:")
print(np.vstack([a, b]))     # shape (2, 3)

# hstack — stack horizontally (column-wise)
print("hstack:", np.hstack([a, b]))   # shape (6,)

# stack — creates a NEW axis
print("stack axis=0:")
print(np.stack([a, b], axis=0))       # shape (2, 3)

print("stack axis=1:")
print(np.stack([a, b], axis=1))       # shape (3, 2)

vstack:
[[1 2 3]
 [4 5 6]]
hstack: [1 2 3 4 5 6]
stack axis=0:
[[1 2 3]
 [4 5 6]]
stack axis=1:
[[1 4]
 [2 5]
 [3 6]]


### 9.3 Splitting:

Splitting is the process of dividing one array into multiple smaller arrays along a specified axis.

In [56]:
arr = np.arange(12).reshape(4, 3)
print("Original (4x3):")
print(arr)

# Split into 2 equal parts along axis=0
parts = np.split(arr, 2, axis=0)
print("\nSplit into 2 parts (axis=0):")
for i, p in enumerate(parts):
    print(f"Part {i}: shape {p.shape}")
    print(p)

Original (4x3):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Split into 2 parts (axis=0):
Part 0: shape (2, 3)
[[0 1 2]
 [3 4 5]]
Part 1: shape (2, 3)
[[ 6  7  8]
 [ 9 10 11]]


In [59]:
# vsplit and hsplit
arr = np.arange(16).reshape(4, 4)

top, bottom = np.vsplit(arr, 2)   # split into top/bottom halves
left, right = np.hsplit(arr, 2)   # split into left/right halves
print("Original (4x4):")
print(arr)
print("vsplit top:")
print(top)
print("vsplit bottom:")
print(bottom)
print("hsplit left:")
print(left)
print("hsplit right:")
print(right)

Original (4x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
vsplit top:
[[0 1 2 3]
 [4 5 6 7]]
vsplit bottom:
[[ 8  9 10 11]
 [12 13 14 15]]
hsplit left:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
hsplit right:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


<a id='10'></a>
## 10. ➕ Mathematical Operations

NumPy performs operations **element-wise** — no loops needed!

### 10.1 Basic Arithmetic :

Arithmetic operations are mathematical operations performed on array elements, such as addition, subtraction, multiplication, division, and exponentiation.

In [60]:
a = np.array([10, 20, 30, 40])
b = np.array([1,  2,  3,  4])

print("a =", a)
print("b =", b)
print()
print("a + b  =", a + b)          # element-wise addition
print("a - b  =", a - b)          # element-wise subtraction
print("a * b  =", a * b)          # element-wise multiplication
print("a / b  =", a / b)          # element-wise division
print("a // b =", a // b)         # floor division
print("a % b  =", a % b)          # modulo
print("a ** 2 =", a ** 2)         # element-wise power
print("a ** b =", a ** b)         # element-wise power

a = [10 20 30 40]
b = [1 2 3 4]

a + b  = [11 22 33 44]
a - b  = [ 9 18 27 36]
a * b  = [ 10  40  90 160]
a / b  = [10. 10. 10. 10.]
a // b = [10 10 10 10]
a % b  = [0 0 0 0]
a ** 2 = [ 100  400  900 1600]
a ** b = [     10     400   27000 2560000]


In [61]:
# ── Scalar Operations (applied to every element) ──
arr = np.array([1, 2, 3, 4, 5])
print("arr      :", arr)
print("arr + 10 :", arr + 10)     # add 10 to every element
print("arr * 3  :", arr * 3)      # multiply every element by 3
print("arr / 2  :", arr / 2)      # divide every element by 2
print("arr ** 2 :", arr ** 2)     # square every element

arr      : [1 2 3 4 5]
arr + 10 : [11 12 13 14 15]
arr * 3  : [ 3  6  9 12 15]
arr / 2  : [0.5 1.  1.5 2.  2.5]
arr ** 2 : [ 1  4  9 16 25]


### 10.2 Universal Functions (ufuncs)

Universal functions (ufuncs) are NumPy functions that perform element-wise operations on arrays efficiently and support operations such as mathematical, trigonometric, and comparison calculations.

In [62]:
arr = np.array([1, 4, 9, 16, 25])

# Math ufuncs
print("sqrt   :", np.sqrt(arr))        # square root
print("abs    :", np.abs([-1,-2,3]))   # absolute value
print("square :", np.square([1,2,3]))  # x^2
print("cbrt   :", np.cbrt([8,27,64]))  # cube root

sqrt   : [1. 2. 3. 4. 5.]
abs    : [1 2 3]
square : [1 4 9]
cbrt   : [2. 3. 4.]


In [63]:
# Exponential and Logarithm
arr = np.array([0, 1, 2, 3])
print("exp(arr) :", np.exp(arr))         # e^x
print("exp2(arr):", np.exp2(arr))        # 2^x

arr_pos = np.array([1, np.e, np.e**2, 10])
print("log(arr) :", np.log(arr_pos))     # natural log ln(x)
print("log2(arr):", np.log2([1,2,4,8]))  # log base 2
print("log10    :", np.log10([1,10,100]))# log base 10

exp(arr) : [ 1.          2.71828183  7.3890561  20.08553692]
exp2(arr): [1. 2. 4. 8.]
log(arr) : [0.         1.         2.         2.30258509]
log2(arr): [0. 1. 2. 3.]
log10    : [0. 1. 2.]


In [64]:
# Trigonometric
angles = np.linspace(0, np.pi, 5)   # 0, π/4, π/2, 3π/4, π
print("angles in radians:", np.round(angles, 2))
print("sin(angles):", np.round(np.sin(angles), 2))
print("cos(angles):", np.round(np.cos(angles), 2))

# Useful constants
print("\nNumPy constants:")
print("np.pi  =", np.pi)   # 3.14159...
print("np.e   =", np.e)    # 2.71828...
print("np.inf =", np.inf)  # infinity
print("np.nan =", np.nan)  # not a number

angles in radians: [0.   0.79 1.57 2.36 3.14]
sin(angles): [0.   0.71 1.   0.71 0.  ]
cos(angles): [ 1.    0.71  0.   -0.71 -1.  ]

NumPy constants:
np.pi  = 3.141592653589793
np.e   = 2.718281828459045
np.inf = inf
np.nan = nan


### 10.3 Rounding Functions :

Rounding functions are NumPy functions used to round numerical array values to a specified number of decimal places or to the nearest integer.

In [65]:
arr = np.array([1.2, 2.5, 3.7, -1.2, -2.5])
print("Original :", arr)
print("round    :", np.round(arr))      # round to nearest integer
print("round(1) :", np.round(arr, 1))   # round to 1 decimal
print("floor    :", np.floor(arr))      # round DOWN
print("ceil     :", np.ceil(arr))       # round UP
print("trunc    :", np.trunc(arr))      # truncate decimal part

Original : [ 1.2  2.5  3.7 -1.2 -2.5]
round    : [ 1.  2.  4. -1. -2.]
round(1) : [ 1.2  2.5  3.7 -1.2 -2.5]
floor    : [ 1.  2.  3. -2. -3.]
ceil     : [ 2.  3.  4. -1. -2.]
trunc    : [ 1.  2.  3. -1. -2.]


### 10.4 Activation Functions (ML Context) :

Activation functions are mathematical functions used in machine learning models, especially neural networks, to introduce non-linearity and determine the output of a neuron based on its input.

In [68]:
# ── Implementing ML Activation Functions with NumPy ──
x = np.linspace(-5, 5, 11)
print("Input x:", x)

# Sigmoid: σ(x) = 1 / (1 + e^(-x))
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# ReLU: max(0, x)
def relu(x):
    return np.maximum(0, x)

# Tanh
def tanh(x):
    return np.tanh(x)

# Softmax: e^x_i / sum(e^x)
def softmax(x):
    e_x = np.exp(x - np.max(x))   # subtract max for numerical stability
    return e_x / e_x.sum()

print("\nSigmoid:", np.round(sigmoid(x), 3))
print("ReLU   :", relu(x))
print("Tanh   :", np.round(tanh(x), 3))

logits = np.array([2.0, 1.0, 0.5, -1.0])
probs  = softmax(logits)
print("\nSoftmax output:", np.round(probs, 4))
print("Sum of softmax :", probs.sum().round(1))   # should be 1.0

Input x: [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]

Sigmoid: [0.007 0.018 0.047 0.119 0.269 0.5   0.731 0.881 0.953 0.982 0.993]
ReLU   : [0. 0. 0. 0. 0. 0. 1. 2. 3. 4. 5.]
Tanh   : [-1.    -0.999 -0.995 -0.964 -0.762  0.     0.762  0.964  0.995  0.999
  1.   ]

Softmax output: [0.6095 0.2242 0.136  0.0303]
Sum of softmax : 1.0


<a id='11'></a>
## 11. 📈 Aggregate / Statistical Functions :

Aggregate and statistical functions are functions used to summarize and analyze array data by calculating values such as the sum, mean, minimum, maximum, variance, and standard deviation.

These functions compute statistics **over entire arrays** or **along specific axes**.

In [69]:
data = np.array([[4,  7, 2, 9],
                 [1,  5, 8, 3],
                 [6, 10, 0, 4]])
print("Data:")
print(data)
print()

Data:
[[ 4  7  2  9]
 [ 1  5  8  3]
 [ 6 10  0  4]]



In [70]:
# ── Basic Statistics ──
print("── Global (entire array) ──")
print("sum    :", np.sum(data))
print("mean   :", np.mean(data))
print("median :", np.median(data))
print("std    :", np.std(data))       # standard deviation
print("var    :", np.var(data))       # variance
print("min    :", np.min(data))
print("max    :", np.max(data))
print("range  :", np.max(data) - np.min(data))

── Global (entire array) ──
sum    : 59
mean   : 4.916666666666667
median : 4.5
std    : 3.0402393911591163
var    : 9.243055555555555
min    : 0
max    : 10
range  : 10


In [71]:
# ── Along Axes ──
print("── Along axis=0 (column-wise, compress rows) ──")
print("sum    :", np.sum(data, axis=0))     # sum of each column
print("mean   :", np.mean(data, axis=0))    # mean of each column
print("max    :", np.max(data, axis=0))     # max of each column

print("\n── Along axis=1 (row-wise, compress columns) ──")
print("sum    :", np.sum(data, axis=1))     # sum of each row
print("mean   :", np.mean(data, axis=1))    # mean of each row
print("max    :", np.max(data, axis=1))     # max of each row

── Along axis=0 (column-wise, compress rows) ──
sum    : [11 22 10 16]
mean   : [3.66666667 7.33333333 3.33333333 5.33333333]
max    : [ 6 10  8  9]

── Along axis=1 (row-wise, compress columns) ──
sum    : [22 17 20]
mean   : [5.5  4.25 5.  ]
max    : [ 9  8 10]


In [74]:
# ── argmin / argmax — index of min/max ──
arr = np.array([3, 1, 7, 2, 9, 4])
print("Array  :", arr)
print("argmin :", np.argmin(arr))    # index of minimum value
print("argmax :", np.argmax(arr))    # index of maximum value

# ML context: in classification, argmax gives the predicted class
classes = np.array(['cat', 'dog', 'rabbit', 'hamster', 'parrot'])
predictions = np.array([0.1, 0.05, 0.8, 0.03, 0.02])
predicted_class = np.argmax(predictions)
print("\nClass probabilities:", predictions)
print("Predicted class    :",   classes[predicted_class])   # class 2 (0-indexed)

Array  : [3 1 7 2 9 4]
argmin : 1
argmax : 4

Class probabilities: [0.1  0.05 0.8  0.03 0.02]
Predicted class    : rabbit


In [75]:
# ── Cumulative functions ──
arr = np.array([1, 2, 3, 4, 5])
print("Array    :", arr)
print("cumsum   :", np.cumsum(arr))   # running total
print("cumprod  :", np.cumprod(arr))  # running product

Array    : [1 2 3 4 5]
cumsum   : [ 1  3  6 10 15]
cumprod  : [  1   2   6  24 120]


In [76]:
# ── Percentile and Quantile ──
data = np.array([2, 5, 8, 12, 15, 20, 25, 30])
print("Data:", data)
print("25th percentile (Q1):", np.percentile(data, 25))
print("50th percentile (Q2/median):", np.percentile(data, 50))
print("75th percentile (Q3):", np.percentile(data, 75))
print("IQR (Q3-Q1):", np.percentile(data, 75) - np.percentile(data, 25))

Data: [ 2  5  8 12 15 20 25 30]
25th percentile (Q1): 7.25
50th percentile (Q2/median): 13.5
75th percentile (Q3): 21.25
IQR (Q3-Q1): 14.0


In [77]:
# ── Handling NaN values ──
data_with_nan = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])
print("Data:", data_with_nan)

print("np.mean    :", np.mean(data_with_nan))      # returns NaN if any NaN
print("np.nanmean :", np.nanmean(data_with_nan))   # ignores NaN
print("np.nansum  :", np.nansum(data_with_nan))
print("np.nanstd  :", np.nanstd(data_with_nan))
print("np.nanmax  :", np.nanmax(data_with_nan))

Data: [ 1.  2. nan  4. nan  6.]
np.mean    : nan
np.nanmean : 3.25
np.nansum  : 13.0
np.nanstd  : 1.920286436967152
np.nanmax  : 6.0


<a id='12'></a>
## 12. 🧮 Linear Algebra with NumPy

Linear Algebra with NumPy refers to using NumPy to perform mathematical operations involving vectors, matrices, and linear equations.

### 12.1 Matrix Multiplication :

Matrix multiplication is the process of multiplying two matrices by multiplying the elements of each row of the first matrix with the corresponding elements of each column of the second matrix and adding the results.

In [78]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

# Matrix multiplication: @ operator or np.matmul or np.dot
# Rule: (m, k) @ (k, n) = (m, n)
# A is (3, 2), B is (2, 3) → result is (3, 3)

C = A @ B             # recommended way
print("A @ B:")
print(C)
print("Shape:", C.shape)

A @ B:
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]
Shape: (3, 3)


In [79]:
# Element-wise vs Matrix multiplication
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("Element-wise (A * B):")
print(A * B)           # multiplies corresponding elements

print("\nMatrix multiply (A @ B):")
print(A @ B)           # true matrix multiplication

Element-wise (A * B):
[[ 5 12]
 [21 32]]

Matrix multiply (A @ B):
[[19 22]
 [43 50]]


### 12.2 np.linalg — Linear Algebra Module:

np.random is NumPy's random module used to generate random numbers, random arrays, and random samples for tasks such as simulations, data generation, and machine learning.

In [80]:
A = np.array([[1., 2.],
              [3., 4.]])

# Determinant
det = np.linalg.det(A)
print("Determinant:", det)

# Inverse (A such that A @ A_inv = Identity)
A_inv = np.linalg.inv(A)
print("\nInverse of A:")
print(A_inv)

# Verify: A @ A_inv should be Identity
print("\nA @ A_inv (should be Identity):")
print(np.round(A @ A_inv, 10))

Determinant: -2.0000000000000004

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]

A @ A_inv (should be Identity):
[[1. 0.]
 [0. 1.]]


In [81]:
# Eigenvalues and Eigenvectors
# Used in PCA (Principal Component Analysis) for dimensionality reduction
A = np.array([[3., 1.],
              [1., 3.]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Matrix A:")
print(A)
print("\nEigenvalues :", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Matrix A:
[[3. 1.]
 [1. 3.]]

Eigenvalues : [4. 2.]
Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [82]:
# Norms — measuring vector/matrix size
v = np.array([3.0, 4.0])

print("Vector:", v)
print("L2 norm (Euclidean):", np.linalg.norm(v))        # sqrt(3²+4²) = 5
print("L1 norm (Manhattan):", np.linalg.norm(v, ord=1))  # 3+4 = 7
print("L∞ norm (Max)      :", np.linalg.norm(v, ord=np.inf))  # max(3,4) = 4

# ML context: L1/L2 regularization uses these norms!

Vector: [3. 4.]
L2 norm (Euclidean): 5.0
L1 norm (Manhattan): 7.0
L∞ norm (Max)      : 4.0


In [83]:
# Solving linear equations: Ax = b
# In ML: used in Normal Equation for Linear Regression
A = np.array([[2., 1.],
              [5., 3.]])
b = np.array([8., 19.])

x = np.linalg.solve(A, b)
print("Solution x:", x)
print("Verify A @ x == b:", np.allclose(A @ x, b))

Solution x: [ 5. -2.]
Verify A @ x == b: True


In [84]:
# Dot product — inner product of two vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot = np.dot(a, b)   # = 1*4 + 2*5 + 3*6 = 4+10+18 = 32
print("Dot product a·b:", dot)

# ML: dot product = cosine similarity (unnormalized)
# High dot product = vectors point in similar direction

Dot product a·b: 32


In [85]:
# Trace — sum of diagonal elements
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("Matrix A:")
print(A)
print("Trace (sum of diagonal):", np.trace(A))  # 1+5+9 = 15
print("Diagonal elements      :", np.diag(A))

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Trace (sum of diagonal): 15
Diagonal elements      : [1 5 9]


<a id='13'></a>
## 13. 🎲 Random Module (np.random)


Random number generation is **essential in ML/DL** — for weight initialization, data shuffling, train/test splits, dropout, and more.

### 13.1 Setting the Seed (Reproducibility) :

Setting a random seed ensures that the same sequence of random numbers is generated each time the code runs, making results reproducible.

In [86]:
# ALWAYS set a seed for reproducibility in ML experiments!
np.random.seed(42)
print("With seed 42:", np.random.rand(5))

np.random.seed(42)   # same seed = same output
print("Same seed 42:", np.random.rand(5))

With seed 42: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
Same seed 42: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


### 13.2 Uniform Distribution:

Uniform distribution is a probability distribution in which all values within a specified range have an equal probability of occurring.

In [87]:
np.random.seed(0)

# rand — uniform distribution [0, 1)
u1 = np.random.rand(5)           # 1D, 5 values
u2 = np.random.rand(3, 4)        # 2D, 3x4 matrix
print("rand(5):", u1)
print("rand(3,4):")
print(u2)

# uniform — uniform distribution [low, high)
u3 = np.random.uniform(low=-1, high=1, size=(2, 3))
print("\nuniform(-1, 1):")
print(u3)

rand(5): [0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
rand(3,4):
[[0.64589411 0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492 0.56804456]
 [0.92559664 0.07103606 0.0871293  0.0202184 ]]

uniform(-1, 1):
[[ 0.66523969  0.5563135   0.7400243 ]
 [ 0.95723668  0.59831713 -0.07704128]]


### 13.3 Normal (Gaussian) Distribution:

Normal (Gaussian) distribution is a continuous probability distribution in which data is symmetrically distributed around its mean, forming a bell-shaped curve.

In [88]:
np.random.seed(0)

# randn — standard normal (mean=0, std=1)
n1 = np.random.randn(5)
n2 = np.random.randn(3, 3)
print("randn(5):", n1)
print("randn(3,3):")
print(n2)

# normal — normal distribution with custom mean and std
n3 = np.random.normal(loc=5.0, scale=2.0, size=1000)  # mean=5, std=2
print("\nnormal(mean=5, std=2):")
print(f"  Mean: {n3.mean():.2f} (expected 5.0)")
print(f"  Std : {n3.std():.2f}  (expected 2.0)")

randn(5): [1.76405235 0.40015721 0.97873798 2.2408932  1.86755799]
randn(3,3):
[[-0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357]
 [ 1.45427351  0.76103773  0.12167502]]

normal(mean=5, std=2):
  Mean: 4.90 (expected 5.0)
  Std : 1.97  (expected 2.0)


### 13.4 Integer Random Numbers:

Integer random numbers are randomly generated whole numbers within a specified range.

In [ ]:
np.random.seed(0)

# randint — random integers [low, high)
r1 = np.random.randint(0, 10, size=8)          # 8 integers from 0-9
r2 = np.random.randint(0, 100, size=(3, 4))    # 3x4 matrix of 0-99

print("randint(0, 10, 8):", r1)
print("randint(0, 100, (3,4)):")
print(r2)

# ML context: simulating class labels
labels = np.random.randint(0, 5, size=20)   # 20 random labels for 5 classes
print("\nRandom class labels:", labels)

### 13.5 Shuffling and Sampling:

Shuffling: Randomly rearranging the order of elements in an array or dataset.

Sampling: Randomly selecting one or more elements from an array or dataset.

In [ ]:
np.random.seed(42)

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# shuffle — randomly rearrange IN PLACE
arr_copy = arr.copy()
np.random.shuffle(arr_copy)
print("Original :", arr)
print("Shuffled :", arr_copy)

# permutation — returns a shuffled copy
perm = np.random.permutation(arr)
print("Permutation:", perm)

# ML: shuffling training data before each epoch
indices = np.random.permutation(len(arr))  # shuffle indices
print("Shuffled indices:", indices)

In [ ]:
np.random.seed(0)

# choice — randomly pick elements
population = np.arange(100)

# Pick 5 random samples WITH replacement
s1 = np.random.choice(population, size=5, replace=True)
print("With replacement   :", s1)

# Pick 5 random samples WITHOUT replacement
s2 = np.random.choice(population, size=5, replace=False)
print("Without replacement:", s2)

### 13.6 Other Distributions:

Other distributions are probability distributions, besides the uniform and normal distributions, used to model different types of data and random events according to their specific patterns and characteristics.

In [ ]:
np.random.seed(0)

# Binomial — number of successes in n trials with probability p
binom = np.random.binomial(n=10, p=0.5, size=8)
print("Binomial(n=10, p=0.5):", binom)

# Poisson — events per interval
pois = np.random.poisson(lam=3.0, size=8)
print("Poisson(lam=3)       :", pois)

# Exponential — time between events
exp = np.random.exponential(scale=1.0, size=5)
print("Exponential(scale=1) :", np.round(exp, 3))

<a id='14'></a>
## 14. 🔀 Sorting & Searching

### 14.1 Sorting
Arranging array elements in a specific order, such as ascending or descending order.


In [ ]:
arr = np.array([3, 1, 7, 2, 9, 4, 6, 5, 8])
print("Original:", arr)

# np.sort — returns sorted COPY (original unchanged)
sorted_asc  = np.sort(arr)
sorted_desc = np.sort(arr)[::-1]
print("Ascending  :", sorted_asc)
print("Descending :", sorted_desc)

In [ ]:
# argsort — returns INDICES that would sort the array
arr = np.array([3, 1, 7, 2, 9])
indices = np.argsort(arr)
print("Array  :", arr)
print("argsort:", indices)         # index order to sort: 1, 3, 0, 2, 4
print("Sorted :", arr[indices])    # use indices to sort

# ML context: get top-k predictions
probs = np.array([0.05, 0.10, 0.60, 0.20, 0.05])
top_k_indices = np.argsort(probs)[::-1][:3]   # top 3 classes
print("\nClass probabilities:", probs)
print("Top-3 class indices:", top_k_indices)

In [ ]:
# Sorting 2D arrays along axes
matrix = np.array([[3, 1, 4],
                   [1, 5, 9],
                   [2, 6, 5]])
print("Original:")
print(matrix)

print("\nSorted along axis=0 (each column sorted):")
print(np.sort(matrix, axis=0))

print("\nSorted along axis=1 (each row sorted):")
print(np.sort(matrix, axis=1))

### 14.2 Searching:
Finding the position or location of specific values or elements within an array.

In [ ]:
arr = np.array([5, 2, 8, 1, 9, 3, 7])
print("Array:", arr)

# np.where — find indices where condition is True
indices = np.where(arr > 5)
print("Indices where arr > 5:", indices[0])
print("Values  where arr > 5:", arr[indices])

# np.where as ternary: where(condition, if_true, if_false)
result = np.where(arr > 5, arr, 0)  # keep values > 5, else replace with 0
print("np.where(arr>5, arr, 0):", result)

In [ ]:
# np.searchsorted — find where to insert to maintain sorted order
sorted_arr = np.array([1, 3, 5, 7, 9])
print("Sorted array:", sorted_arr)
print("Insert 4 at index:", np.searchsorted(sorted_arr, 4))   # index 2
print("Insert 6 at index:", np.searchsorted(sorted_arr, 6))   # index 3

# np.nonzero — indices of non-zero elements
arr = np.array([0, 1, 0, 3, 0, 5])
print("\nNon-zero indices:", np.nonzero(arr)[0])
print("Non-zero values :", arr[np.nonzero(arr)])

<a id='15'></a>
## 15. ✅ Comparison & Boolean Operations:
Comparison and Boolean operations are operations used to compare array elements and produce Boolean (True or False) results based on specified conditions.

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

# Element-wise comparisons — return boolean arrays
print("a =", a)
print("b =", b)
print()
print("a == b :", a == b)
print("a != b :", a != b)
print("a >  b :", a >  b)
print("a <  b :", a <  b)
print("a >= b :", a >= b)
print("a <= b :", a <= b)

In [ ]:
# Boolean Indexing — filter array using boolean mask
arr = np.array([10, 25, 5, 30, 15, 45, 8])
print("Array:", arr)

mask = arr > 15
print("Mask (arr > 15) :", mask)
print("Filtered values  :", arr[mask])

# Combined conditions
mask2 = (arr > 10) & (arr < 35)   # AND
print("10 < arr < 35  :", arr[mask2])

mask3 = (arr < 10) | (arr > 30)   # OR
print("arr<10 OR arr>30:", arr[mask3])

In [ ]:
# Logical Functions
a = np.array([True, True, False, False])
b = np.array([True, False, True, False])

print("a AND b:", np.logical_and(a, b))
print("a OR  b:", np.logical_or(a, b))
print("NOT a  :", np.logical_not(a))
print("a XOR b:", np.logical_xor(a, b))

# any() and all()
arr = np.array([False, True, True, False])
print("\nAny True:", np.any(arr))    # True if at least one is True
print("All True:", np.all(arr))    # True only if all are True

In [ ]:
# Utility comparison functions
a = np.array([1.0, np.nan, np.inf, 2.0])

print("Array:", a)
print("isnan  :", np.isnan(a))       # check for NaN
print("isinf  :", np.isinf(a))       # check for infinity
print("isfinite:", np.isfinite(a))   # check for finite values

# allclose — compare arrays with tolerance (useful for float comparisons)
x = np.array([1.0000001, 2.0000002])
y = np.array([1.0,       2.0      ])
print("\nnp.allclose(x, y):", np.allclose(x, y))  # True (within tolerance)

<a id='16'></a>
## 16. 🤖 NumPy in ML & DL Context

Putting everything together — real ML/DL workflows using pure NumPy.

### 16.1 Data Normalization & Standardization

Data Normalization: Rescaling data to a fixed range, usually 0 to 1.

Data Standardization: Transforming data so that it has a mean of 0 and a standard deviation of 1.

In [ ]:
np.random.seed(42)
data = np.random.randint(10, 200, size=(5, 4)).astype(float)
print("Raw data:")
print(data)

# ── Min-Max Normalization → scales to [0, 1] ──
data_min  = data.min(axis=0)    # column-wise min
data_max  = data.max(axis=0)    # column-wise max
normalized = (data - data_min) / (data_max - data_min)
print("\nMin-Max Normalized (column-wise):")
print(np.round(normalized, 3))

# ── Z-Score Standardization → mean=0, std=1 ──
data_mean = data.mean(axis=0)
data_std  = data.std(axis=0)
standardized = (data - data_mean) / data_std
print("\nZ-Score Standardized (column-wise):")
print(np.round(standardized, 3))
print("Column means after standardization:", np.round(standardized.mean(axis=0), 5))
print("Column stds  after standardization:", np.round(standardized.std(axis=0),  5))

### 16.2 Train-Test Split:
Train-Test Split is the process of dividing a dataset into two parts: a training set to train the machine learning model and a testing set to evaluate its performance on unseen data.

In [ ]:
np.random.seed(42)

# Simulate a dataset: 100 samples, 5 features
X = np.random.randn(100, 5)    # features
y = np.random.randint(0, 2, 100)  # binary labels

# Shuffle indices
indices = np.random.permutation(len(X))

# 80% train, 20% test
split = int(0.8 * len(X))
train_idx = indices[:split]
test_idx  = indices[split:]

X_train, X_test = X[train_idx], X[test_idx]
y_train, y_test = y[train_idx], y[test_idx]

print(f"Total samples : {len(X)}")
print(f"Training set  : {X_train.shape}")
print(f"Testing set   : {X_test.shape}")

### 16.3 Linear Regression from Scratch:
Linear Regression from Scratch is implementing a linear regression model manually using basic Python and NumPy, without using a ready-made machine learning model such as sklearn.linear_model.LinearRegression.

In [ ]:
np.random.seed(42)

# Generate synthetic data: y = 3x + 2 + noise
X = np.linspace(0, 10, 50).reshape(-1, 1)   # (50, 1)
y = 3 * X.squeeze() + 2 + np.random.randn(50) * 1.5

# Add bias column (column of 1s)
X_b = np.hstack([np.ones((50, 1)), X])       # (50, 2)

# Normal Equation: θ = (X^T X)^{-1} X^T y
theta = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y

print("Learned parameters:")
print(f"  Intercept (bias): {theta[0]:.4f}  (true: 2.0)")
print(f"  Slope (weight)  : {theta[1]:.4f}  (true: 3.0)")

# Predictions
y_pred = X_b @ theta
mse = np.mean((y - y_pred) ** 2)
print(f"\nMean Squared Error: {mse:.4f}")

### 16.4 Neural Network Forward Pass (Single Layer):
A Neural Network Forward Pass is the process of passing input data through a single layer of a neural network to calculate the output using weights, bias, and an activation function.

In [ ]:
np.random.seed(42)

# ── Single layer: input → hidden ──
batch_size    = 8
input_features = 4
hidden_units   = 3

# Input data
X = np.random.randn(batch_size, input_features)   # (8, 4)

# Weights (Xavier initialization)
W = np.random.randn(input_features, hidden_units) * np.sqrt(2.0 / input_features)

# Bias
b = np.zeros(hidden_units)                         # (3,)

# Linear transformation: Z = X @ W + b
Z = X @ W + b                                      # (8, 3)

# Activation: ReLU
A = np.maximum(0, Z)                               # (8, 3)

print("Input  X shape:", X.shape)
print("Weight W shape:", W.shape)
print("Bias   b shape:", b.shape)
print("Pre-activation Z shape:", Z.shape)
print("Post-activation A shape:", A.shape)
print("\nOutput after ReLU:")
print(np.round(A, 3))

### 16.5 One-Hot Encoding:
One-Hot Encoding is a technique that converts categorical values into separate binary columns containing 0 and 1 so that machine learning models can process them.

In [ ]:
# One-Hot Encoding — converts class labels to binary vectors
# e.g., class 2 out of 4 classes → [0, 0, 1, 0]

labels = np.array([0, 2, 1, 3, 0, 2])  # 4 possible classes (0-3)
num_classes = 4

# Create identity matrix and index into it
one_hot = np.eye(num_classes)[labels]

print("Class labels:", labels)
print("One-Hot Encoded:")
print(one_hot)

### 16.6 Batch Processing:
Batch Processing is the process of dividing data into smaller groups called batches and processing each batch together instead of processing the entire dataset at once.

In [ ]:
# Processing data in mini-batches (standard in DL training)
np.random.seed(0)

dataset = np.random.randn(100, 5)   # 100 samples, 5 features
batch_size = 16
num_batches = len(dataset) // batch_size

print(f"Dataset: {dataset.shape}")
print(f"Batch size: {batch_size}")
print(f"Number of full batches: {num_batches}")
print()

for i in range(num_batches):
    batch = dataset[i * batch_size : (i + 1) * batch_size]
    batch_mean = batch.mean(axis=0)
    if i < 3:   # print first 3 batches
        print(f"Batch {i+1}: shape={batch.shape}, mean[0]={batch_mean[0]:.3f}")

---

## 🎯 Quick Reference Cheatsheet

| Category | Function | Purpose |
|----------|----------|---------|
| **Create** | `np.array()` | From list |
| | `np.zeros(shape)` | All zeros |
| | `np.ones(shape)` | All ones |
| | `np.eye(n)` | Identity matrix |
| | `np.arange(start,stop,step)` | Range |
| | `np.linspace(start,stop,n)` | Evenly spaced |
| **Attributes** | `.shape` | Dimensions |
| | `.dtype` | Data type |
| | `.ndim` | Number of axes |
| | `.size` | Total elements |
| **Reshape** | `.reshape(shape)` | Change shape |
| | `.flatten()` | To 1D (copy) |
| | `.T` | Transpose |
| | `np.expand_dims` | Add axis |
| **Math** | `np.sqrt, exp, log` | Element-wise math |
| | `np.maximum(0, x)` | ReLU |
| | `1/(1+np.exp(-x))` | Sigmoid |
| **Stats** | `np.mean, std, var` | Statistics |
| | `np.min, max, sum` | Aggregates |
| | `np.argmax, argmin` | Index of extreme |
| **Linear Alg** | `A @ B` | Matrix multiply |
| | `np.linalg.inv` | Inverse |
| | `np.linalg.norm` | Norm |
| **Random** | `np.random.seed` | Reproducibility |
| | `np.random.randn` | Normal dist |
| | `np.random.randint` | Random integers |
| | `np.random.shuffle` | Shuffle in-place |
| **Search** | `np.where` | Conditional filter |
| | `np.argsort` | Sort indices |

---

## 🏁 Summary

In this notebook we covered:

✅ **What NumPy is** and why it's faster than Python lists  
✅ **Creating arrays** — from lists, zeros, ones, ranges, random  
✅ **Array attributes** — shape, dtype, ndim, size, strides  
✅ **Data types** — int, float, bool and type casting  
✅ **Indexing & Slicing** — 1D and 2D, views vs copies  
✅ **Reshaping** — reshape, flatten, transpose, expand_dims  
✅ **Manipulation** — concatenate, stack, split  
✅ **Math operations** — arithmetic, ufuncs, activation functions  
✅ **Statistics** — mean, std, percentile, NaN handling  
✅ **Linear Algebra** — matmul, inverse, eigenvalues, norms  
✅ **Random** — seeding, distributions, shuffling, sampling  
✅ **Sorting & Searching** — sort, argsort, where, nonzero  
✅ **Boolean operations** — masks, logical operators  
✅ **ML/DL applications** — normalization, train-test split, forward pass  